language: minimal
branches:
    only:
        - master
cache:
    directories:
        - node_modules
before_install:
    - bun update
install:
    - bun install
script:
    - bun test
    - bun run coveralls
